pub mod author;
pub mod resource;

pub mod test {
    pub const SPIGOT_BASE64_TEST_ICON_DATA: &str = "iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAMAAADVRocKAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAABpUExURQAA/9UAnP8AAAYA/9MAnP8GAACc1gCc1F2c5aGc/5yc/5Gh/+RdnAD/AKH/lP////+hnAD/IZz/nv+cnJz/o/+RoQD/BZz/Yf//of//nP/kXf/TAP/VAAD/JJz/AP//AP//BgD/Ipz/Gh6xHjkAAAAJcEhZcwAADsIAAA7CARUoSoAAAACiSURBVGhD7c03EsNQDAPR7xzlHOQo2/c/pFWgJTEjtfsaNhxs6WkwNPTXGQGLgEXAImARsAhYBCwCFgGLQBnpRsYTDUXKNDebL5aJ1Vo7oVIZm21qp51Q2eeqg5YCR+2ECBAgQIBAiwABAgRaBPoHTloKnLUTcoHLtb4l6vvjmXOB17vJfXQjLvD96bErAhYBi4BFwCJgEbAIWAQsAhYBo2n+jQfQ7wOAIcwAAAAASUVORK5CYII=";
}